'use strict';

const readonly = 'readonly';

const runtimeGlobals = {
  AbortController: readonly,
  AbortSignal: readonly,
  Blob: readonly,
  console: readonly,
  CustomEvent: readonly,
  DOMException: readonly,
  Event: readonly,
  EventTarget: readonly,
  fetch: readonly,
  File: readonly,
  FormData: readonly,
  Headers: readonly,
  performance: readonly,
  queueMicrotask: readonly,
  Request: readonly,
  Response: readonly,
  setInterval: readonly,
  clearInterval: readonly,
  setTimeout: readonly,
  clearTimeout: readonly,
  structuredClone: readonly,
  TextDecoder: readonly,
  TextEncoder: readonly,
  URL: readonly,
  URLSearchParams: readonly,
};

const nodeGlobals = {
  ...runtimeGlobals,
  __dirname: readonly,
  __filename: readonly,
  Buffer: readonly,
  clearImmediate: readonly,
  exports: readonly,
  module: readonly,
  process: readonly,
  require: readonly,
  setImmediate: readonly,
};

const browserGlobals = {
  ...runtimeGlobals,
  alert: readonly,
  cancelAnimationFrame: readonly,
  confirm: readonly,
  CSS: readonly,
  document: readonly,
  DOMParser: readonly,
  Element: readonly,
  FileReader: readonly,
  EventSource: readonly,
  getComputedStyle: readonly,
  history: readonly,
  Image: readonly,
  localStorage: readonly,
  location: readonly,
  matchMedia: readonly,
  MutationObserver: readonly,
  navigator: readonly,
  Node: readonly,
  prompt: readonly,
  requestAnimationFrame: readonly,
  ResizeObserver: readonly,
  sessionStorage: readonly,
  window: readonly,
  DOMPurify: readonly,
  EasyMDE: readonly,
  L: readonly,
  cytoscape: readonly,
  cytoscapeDagre: readonly,
  dagre: readonly,
  marked: readonly,
};

module.exports = [
  {
    ignores: [
      'data/**',
      'data-snapshots/**',
      'docs/plans/**',
      'node_modules/**',
    ],
  },
  {
    files: ['**/*.{js,cjs,mjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
    },
    rules: {
      'array-callback-return': 'error',
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['error', 'except-parens'],
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'error',
      'no-empty-character-class': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-obj-calls': 'error',
      'no-promise-executor-return': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unexpected-multiline': 'error',
      'no-undef': 'error',
      'no-unreachable': 'error',
      'no-unreachable-loop': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        caughtErrors: 'none',
        varsIgnorePattern: '^_',
      }],
      'no-useless-assignment': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
  },
  {
    files: [
      'server.js',
      'server-utils.cjs',
      'tiler.js',
      'scripts/**/*.{js,cjs,mjs}',
      'server/**/*.{js,cjs,mjs}',
      'test/**/*.{js,cjs,mjs}',
    ],
    languageOptions: {
      globals: nodeGlobals,
    },
  },
  {
    files: [
      'web/**/*.{js,cjs,mjs}',
      'examples/addons/**/*.{js,cjs,mjs}',
    ],
    languageOptions: {
      globals: browserGlobals,
    },
  },
];
